apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-linkeun-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-linkeun-com
  template:
    metadata:
      labels:
        app: api-linkeun-com
    spec:
      containers:
        - name: api-linkeun-com
          image: "linkeunid/api.linkeun.com:latest"
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
            - name: DSN
              value: "root:root@tcp(mariadb:6603)/linkeun?charset=utf8&parseTime=True&loc=Local"
            - name: SENTRY_DSN
              value: ""
          ports:
            - containerPort: 4444

---
apiVersion: v1
kind: Service
metadata:
  name: api-linkeun-com
spec:
  selector:
    app: api-linkeun-com
  ports:
    - protocol: TCP
      name: http-port
      port: 4444
      targetPort: 4444
